name: itch.io upload

# define what triggers the action
# in this case: on push if one of the files named in paths changes
on:
  push:
    paths:
      - "version"
      - ".github/workflows/upload-itchio-remote.yml"

# the directory where your game is
# I always put the game inside a 'game' folder
env:
  WORKING_DIRECTORY: remote_work

jobs:
  deploy:
    # only run action, if pushed on main branch
    # change or remove according to your needs
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      # change or remove according to your needs
      - name: Create export directory
        run: mkdir html5

      # exports the game in html mode
      # more info here https://github.com/dulvui/godot-html-export
      - name: Godot HTML5 export
        uses: Kwpa/godot-html-export@v0.2.3
        with:
          working-directory: $WORKING_DIRECTORY

      # uploads to itch.io
      # more info here https://github.com/dulvui/itchio-butler-upload
      - name: Upload to itch.io
        uses: Kwpa/itchio-butler-upload@v0.1.1
        with:
          working-directory: html5
          api-key: ${{ secrets.ITCHIO_API_KEY }}
          user: varoxolotl
          game: remote-work
          channel: html5